#ScenicView properties
#Thu Oct 01 09:03:37 CEST 2026
autoRefreshStyleSheets=false
automaticScenegraphStructureRefreshing=true
collapseContainerControls=false
collapseControls=true
ignoreMouseTransparentNodes=true
registerShortcuts=true
showBaseline=false
showBounds=true
showCSSProperties=false
showDefaultProperties=true
showFilteredNodesInTree=true
showInvisibleNodes=false
showNodesIdInTree=false
showSearchBar=true
splitPaneDividerPosition=0.550625
stageHeight=800.0
stageWidth=800.0
